prompt_order = [
    "username",
    "hostname",
    "kubernetes",
    "git_branch",
    "git_commit",
    "git_state",
    "git_status",
    "hg_branch",
    "package",
    "dotnet",
    "golang",
    "java",
    "nodejs",
    "php",
    "python",
    "ruby",
    "rust",
    "terraform",
    "nix_shell",
    "conda",
    "memory_usage",
    "aws",
    "env_var",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "time",
    "directory",
    "character",
]

[aws]
symbol = "🅰 "

[battery]
disabled = true

[conda]
disabled = true

[directory]
prefix = ""

[dotnet]
disabled = true

[env_var]
disabled = true

[hostname]
ssh_only = false

[username]
show_always = true
style_user = "blue"

[time]
disabled = false
style = "blue"
