format = """\
    $username\
    $hostname\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $package\
    $python\
    $rust\
    $terraform\
    $nix_shell\
    $aws\
    $cmd_duration\
    $line_break\
    $time\
    $directory\
    $character\
"""

[aws]
symbol = "🅰 "

[battery]
disabled = true

[conda]
disabled = true

[dotnet]
disabled = true

[env_var]
disabled = true

[hostname]
ssh_only = false
format = "@[$hostname]($style) "

[username]
show_always = true
style_user = "bright-blue"
format = "[$user]($style)"

[time]
disabled = false
style = "blue"
utc_time_offset = "0"
format = "[$time]($style) "
