# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "k10temp" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.kernelParams = [ "quiet" ];
  boot.extraModulePackages = with pkgs.linuxPackages_latest; [ ];

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-partlabel/nixos";

  fileSystems."/" =
    {
      device = "/dev/disk/by-label/nixos";
      fsType = "ext4";
    };

  fileSystems."/home/wkral/usb" =
    {
      device = "/dev/disk/by-label/3TB";
      fsType = "ext4";
      options = [ "nofail" "x-systemd.automount" ];
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-partlabel/boot";
      fsType = "vfat";
    };

  swapDevices = [
    {
      device = "/dev/disk/by-partlabel/swap";
      randomEncryption.enable = true;
    }
  ];

  services.fstrim.enable = true;

  hardware.cpu.amd.updateMicrocode = true;

  nix.settings.max-jobs = lib.mkDefault 12;
}
